version: "3.7"

services:
  pet-charity-server:
    image: alexandersvirzhevsky/pet-charity-server:prod-1
    build:
      context: .
      dockerfile: Dockerfile.production
      target: prod
    container_name: pet-charity-server
    restart: always
    ports:
      - "80:5000"
