FROM node:16 as prod

WORKDIR /app

COPY package*.json ./

RUN npm install

WORKDIR /app/client

RUN git clone https://github.com/alexander-svirzhevsky/pet-charity-fe.git .

RUN npm install

RUN npm run build

WORKDIR /app

COPY . .

ENV NODE_ENV=production

CMD [ "npm", "start" ]
